<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Exceções</title>
    <style>
        .centralizar{
            text-align: center;
        }
        .campos{
            background-color: bisque;
            height: auto;
            width: 50%;
            border-radius: 10px;
            box-shadow: 5px 5px 10px rgba(0, 0, 0, .6);
            padding: 10px;
            margin: auto;
            position: relative;
            margin-bottom: 10px;
        }
    </style>
</head>
<body>  
    <header>
        <p class="centralizar">Teste Exceções 02</p>
    </header>
    <section>
        <div class="campos">
           <p class="centralizar"><label>Digite um número entre 0 e 9: </label><input type="number" id='num'></p>
           <p class="centralizar"><input type="submit" value="Go!" onclick="Analisar()"></p>
        </div>
    </section>
    <footer>
        <p class="centralizar"> &copy; Vinicius Cavalcante</p>
    </footer>
    <script>
        /* uso da declaração throw para personalizar a mensagem de erro sem criar referência para o erro. */

        function Analisar(){
            var x = document.getElementById('num').value;
            
            try {
                if(x < 0) throw new Error ("O número digitado é menor que 0."); //Passar uma string para o objeto Error com o uso do operador new altera a propriedade message padrão do objeto para o valor da string
                if(x > 9) throw new Error ("O número digitado é maior que 9.");
            } catch (error) {
                alert(error.message); //Mostra a mensagem passada para o atributo message do objeto error
            } finally { //ocorre mesmo que a exceção seja lançada ou não
                alert(`O número digitado foi ${x}`);
            }
        }
    </script>
</body>
</html>